version: '3.7'

services:
  web-app:
    build: .
    restart: always
    entrypoint: "/code/start.sh"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5555/fastapi_app_db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    command: -p 5555
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_app_db
    expose:
      - 5555
    ports:
      - "5555:5555"

volumes:
  postgres_data: