"""004_manytomany_users_events

Revision ID: bc6ca3061404
Revises: aa65a6a0d9d5
Create Date: 2024-08-14 22:29:45.706568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6ca3061404'
down_revision: Union[str, None] = 'aa65a6a0d9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_users',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.add_column('events', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('events', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('events', 'name')
    op.drop_table('events_users')
    # ### end Alembic commands ###
